package ab

var (
	ProgramNameVersion       = "Program AB 0.0.6.26 beta -- AI Foundation Reference AIML 2.1 implementation"
	Comment                  = "Added repetition detection."
	AimlifSplitChar          = ","
	DefaultBot               = "alice2"
	DefaultLanguage          = "EN"
	AimlifSplitCharName      = "\\#Comma"
	AimlifFileSuffix         = ".csv"
	AbSampleFile             = "sample.txt"
	TextCommentMark          = ";;"
	PannousApiKey            = "guest"
	PannousLogin             = "test-user"
	SraixFailed              = "SRAIXFAILED"
	RepetitionDetected       = "REPETITIONDETECTED"
	SraixNoHint              = "nohint"
	SraixEventHint           = "event"
	SraixPicHint             = "pic"
	SraixShoppingHint        = "shopping"
	UnknownAimlFile          = "unknownAimlFile.aiml"
	DeletedAimlFile          = "deleted.aiml"
	LearnfAimlFile           = "learnf.aiml"
	NullAimlFile             = "null.aiml"
	InappropriateAimlFile    = "inappropriate.aiml"
	ProfanityAimlFile        = "profanity.aiml"
	InsultAimlFile           = "insults.aiml"
	ReductionsUpdateAimlFile = "reductions_update.aiml"
	PredicatesAimlFile       = "client_profile.aiml"
	UpdateAimlFile           = "update.aiml"
	PersonalityAimlFile      = "personality.aiml"
	SraixAimlFile            = "sraix.aiml"
	OobAimlFile              = "oob.aiml"
	UnfinishedAimlFile       = "unfinished.aiml"
	InappropriateFilter      = "FILTER INAPPROPRIATE"
	ProfanityFilter          = "FILTER PROFANITY"
	InsultFilter             = "FILTER INSULT"
	DeletedTemplate          = "deleted"
	UnfinishedTemplate       = "unfinished"
	BadJavascript            = "JSFAILED"
	JsEnabled                = "true"
	UnknownHistoryItem       = "unknown"
	DefaultBotResponse       = "I have no answer for that."
	ErrorBotResponse         = "Something is wrong with my brain."
	ScheduleError            = "I'm unable to schedule that event."
	SystemFailed             = "Failed to execute system command."
	DefaultGet               = "unknown"
	DefaultProperty          = "unknown"
	DefaultMap               = "unknown"
	DefaultCustomerId        = "unknown"
	DefaultBotName           = "unknown"
	DefaultThat              = "unknown"
	DefaultTopic             = "unknown"
	DefaultListItem          = "NIL"
	UndefinedTriple          = "NIL"
	UnboundVariable          = "unknown"
	TemplateFailed           = "Template failed."
	TooMuchRecursion         = "Too much recursion in AIML"
	TooMuchLooping           = "Too much looping in AIML"
	BlankTemplate            = "blank template"
	NullInput                = "NORESP"
	NullStar                 = "nullstar"
	SetMemberString          = "ISA"
	RemoteMapKey             = "external"
	RemoteSetKey             = "external"
	NaturalNumberSetName     = "number"
	MapSuccessor             = "successor"
	MapPredecessor           = "predecessor"
	MapSingular              = "singular"
	MapPlural                = "plural"
	RootPath                 = "c:/ab"
)

func SetRootPath(newRootPath string) {
	RootPath = newRootPath
}

func SetRootPathFromSystem() {
	// Simulate System.getProperty("user.dir")
	// Not directly translatable in Go, use current directory
	SetRootPath(".")
}
